version: "3.6"
services:
  store16:
    image: odoo:16.0
    container_name: store16
    user: root
    ports:
      - 8069:8069
    depends_on:
      - store16-db
    environment:
      - HOST=store16-db
      - USER=odoo
      - PASSWORD=password
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
      - ./logs:/var/log/odoo
  store16-db:
    image: postgres:14
    container_name: store16-db
    user: root
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
